//Includes necessários para o main


#include "tfont.h"
#include "calibri_24.h"
#include "maquina1.h"
#include "conf_board.h"
#include "conf_example.h"
#include "conf_uart_serial.h"
#include "logo.h"
#include "icones/water.h"
#include "icones/water_click.h"
#include "icones/lock_white.h"
#include "icones/unlock_white.h"
#include "icones/fast.h"
#include "icones/fast_click.h"
#include "icones/clean.h"
#include "icones/clean_click.h"
#include "icones/centrifuge.h"
#include "icones/centrifuge_click.h"
#include "icones/daily.h"
#include "icones/daily_click.h"
#include "icones/heavy.h"
#include "icones/heavy_click.h"
